#!/usr/bin/env bash

if [ -f $XDG_CONFIG_HOME/dmenu/.dmenurc ]; then
  . $XDG_CONFIG_HOME/dmenu/.dmenurc
else
  DMENU='dmenu'
fi

oup=$(xsel -o)
while inp=$(echo -e "$oup" | $DMENU -l 10 -p Calculate:)
do
    if oup2=$(calc -pd "$inp"); then
        echo -n "$oup2" | xsel -i
        oup="$oup2\n$oup"
    fi
done
