#!/usr/bin/env bash

if [ -f $XDG_CONFIG_HOME/dmenu/.dmenurc ]; then
  . $XDG_CONFIG_HOME/dmenu/.dmenurc
else
  DMENU='dmenu'
fi

menu_options="open\nlock\nnetwork-connect\nnetwork-add\nbluetooth-connect\nbluetooth-add\ntodo\nscreenshot\nemoji\ncalculate\nwebcam"
prompt="What do you want to do?"

# let the user pick an option
selection=$(echo -e $menu_options | $DMENU $@ -l 15 -p "$prompt:")

case "$selection" in
        open) open ;;
        lock) dm-tool lock ;;
        emoji) emoji & ;;
        todo) todo & ;;
        screenshot) screenshot & ;;
        network-connect) network-connect & ;;
        network-add) network-add & ;;
        bluetooth-connect) bluetooth-connect & ;;
        bluetooth-add) bluetooth-add & ;;
        calculate) calculate & ;;
        webcam) webcam & ;;
esac

exit 0
