#!/usr/bin/env bash

echo $PATH > $HOME/path

if [ -f $XDG_CONFIG_HOME/dmenu/.dmenurc ]; then
  . $XDG_CONFIG_HOME/dmenu/.dmenurc
else
  DMENU='dmenu'
fi

options_file=$XDG_DATA_HOME/dmenu/menu_options

# count the lines and limit them to 30
lines=$(cat $options_file | wc -l)
if [ "$lines" -gt 20 ]; then lines=30; fi

prompt="What do you want to do?"

# let the user pick an option
selection=$(cat "$options_file" | $DMENU $@ -l "$lines" -p "$prompt:")

case "$selection" in
        emoji) emoji & ;;
        todo) todo & ;;
        screenshot) screenshot & ;;
        network-connect) network-connect & ;;
        network-add) network-add & ;;
        bluetooth-connect) bluetooth-connect & ;;
        bluetooth-add) bluetooth-add & ;;
esac

exit 0
